name: smart_pendant_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0' # Check your Flutter version, this is a safe range

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  shared_preferences: ^2.2.3
  flutter_web_auth_2: ^4.1.0
  googleapis: ^13.1.0
  googleapis_auth: ^1.6.0
  app_links: ^6.4.0
  url_launcher: ^6.3.2
  google_fonts: ^6.2.1 
  video_player: ^2.2.19
  animate_do: ^3.3.4
  sensors_plus: ^5.0.1
  audioplayers: ^6.0.0
  just_audio: ^0.9.36  # For sound effects
  animated_text_kit: ^4.2.2
  collection: ^1.18.0
  mobile_scanner: ^5.1.1 # Added for QR code scanning
  wifi_iot: ^0.3.19
  wifi_scan: ^0.4.1+2 # For scanning for Wi-Fi networks

# Here is how you can implement a carousel for your app. The changes involve creating a new screen for the onboarding experience and updating your app's navigation flow to include it right after the login process.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/audio/
    - assets/images/
    - assets/onboarding_1.png
    - assets/onboarding_2.png
    - assets/onboarding_3.png
  